import type { ImageSourcePropType } from 'react-native';

export type IstanbulPlace = { id: string; name: string; district: string; category: string; summary: string; image: ImageSourcePropType; mapQuery: string; credit: string; imagePage: string };
export type IstanbulDistrict = { name: string; side: 'Avrupa' | 'Anadolu' | 'Adalar'; signature: string; mapQuery: string };

const european = ['Arnavutköy','Avcılar','Bağcılar','Bahçelievler','Bakırköy','Başakşehir','Bayrampaşa','Beşiktaş','Beylikdüzü','Beyoğlu','Büyükçekmece','Çatalca','Esenler','Esenyurt','Eyüpsultan','Fatih','Gaziosmanpaşa','Güngören','Kağıthane','Küçükçekmece','Sarıyer','Silivri','Sultangazi','Şişli','Zeytinburnu'];
const asian = ['Ataşehir','Beykoz','Çekmeköy','Kadıköy','Kartal','Maltepe','Pendik','Sancaktepe','Sultanbeyli','Şile','Tuzla','Ümraniye','Üsküdar'];
const signatures: Record<string, string> = {
  Fatih: 'Tarihî yarımada ve imparatorluk mirası', Beyoğlu: 'Galata, İstiklal ve kültür hayatı', Beşiktaş: 'Boğaz, saraylar ve canlı sokaklar',
  Kadıköy: 'Çarşı, sahil ve Anadolu Yakası kültürü', Üsküdar: 'Kız Kulesi, camiler ve Boğaz silüeti', Sarıyer: 'Boğaz köyleri, korular ve müzeler',
  Adalar: 'Köşkler, bisiklet rotaları ve deniz', Şile: 'Karadeniz kıyıları ve doğal koylar', Eyüpsultan: 'Haliç, Pierre Loti ve manevi miras',
};
const district = (name: string, side: IstanbulDistrict['side']): IstanbulDistrict => ({ name, side, signature: signatures[name] ?? (side === 'Avrupa' ? 'Avrupa Yakası kent yaşamı ve yerel keşifler' : side === 'Anadolu' ? 'Anadolu Yakası mahalleleri ve sahil rotaları' : 'Ada yaşamı ve deniz rotaları'), mapQuery: `${name} İstanbul` });

export const istanbulDistricts: IstanbulDistrict[] = [district('Adalar', 'Adalar'), ...european.map(name => district(name, 'Avrupa')), ...asian.map(name => district(name, 'Anadolu'))].sort((a, b) => a.name.localeCompare(b.name, 'tr'));

export const istanbulPlaces: IstanbulPlace[] = [
  { id: 'ayasofya', name: 'Ayasofya', district: 'Fatih', category: 'Tarihî yapı', summary: 'Bizans ve Osmanlı dönemlerinin izlerini bir arada taşıyan, tarihî yarımadanın simge yapılarından biri.', image: require('../assets/istanbul/hagia-sophia.jpg'), mapQuery: 'Ayasofya İstanbul', credit: 'José Luiz · CC BY-SA 3.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Exterior_of_Hagia_Sophia_from_the_Bosphorus.jpg' },
  { id: 'dolmabahce', name: 'Dolmabahçe Sarayı', district: 'Beşiktaş', category: 'Saray', summary: 'Osmanlı’nın son dönem yönetim merkezi; Boğaz kıyısındaki görkemli cephesi, tören salonları ve bahçeleriyle öne çıkar.', image: require('../assets/istanbul/dolmabahce.jpg'), mapQuery: 'Dolmabahçe Sarayı İstanbul', credit: 'flowcomm · CC BY 2.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Dolmabahce_Istanbul_Turkey.jpg' },
  { id: 'topkapi', name: 'Topkapı Sarayı', district: 'Fatih', category: 'Saray', summary: 'Yüzyıllar boyunca Osmanlı yönetiminin merkezi olan saray; avluları, Harem’i ve imparatorluk koleksiyonlarıyla kapsamlı bir durak.', image: require('../assets/istanbul/topkapi.jpg'), mapQuery: 'Topkapı Sarayı İstanbul', credit: 'Yair Haklai · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Gate_of_Salutation_(Topkapı_Palace)-.jpg' },
  { id: 'yerebatan', name: 'Yerebatan Sarnıcı', district: 'Fatih', category: 'Tarihî yapı', summary: '6. yüzyılda inşa edilen yer altı su yapısı; sütunları, yansımaları ve Medusa başlarıyla benzersiz bir tarih atmosferi sunar.', image: require('../assets/istanbul/yerebatan.jpg'), mapQuery: 'Yerebatan Sarnıcı İstanbul', credit: 'Gun Powder Ma · Public domain', imagePage: 'https://commons.wikimedia.org/wiki/File:Basilica_Cistern,_Constantinople.jpg' },
  { id: 'galata', name: 'Galata Kulesi', district: 'Beyoğlu', category: 'Müze · Manzara', summary: 'Galata’nın tarihî sokakları üzerinde yükselen ve panoramik İstanbul manzarası sunan kent simgesi.', image: require('../assets/istanbul/galata.jpg'), mapQuery: 'Galata Kulesi İstanbul', credit: 'Maurice Flesier · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Exterior_view_of_the_Galata_Tower.jpg' },
  { id: 'kiz-kulesi', name: 'Kız Kulesi', district: 'Üsküdar', category: 'Tarihî yapı', summary: 'Boğaz’ın ortasında, Üsküdar kıyısının karşısında yer alan İstanbul’un en tanınan silüetlerinden.', image: require('../assets/istanbul/maiden-tower.jpg'), mapQuery: 'Kız Kulesi İstanbul', credit: 'MB-one · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Maiden_tower,_Istanbul_(P1100206).jpg' },
  { id: 'adalar', name: 'Büyükada ve Adalar', district: 'Adalar', category: 'Doğa · Sahil', summary: 'Tarihî köşkler, bisiklet rotaları, çamlıklar ve Marmara manzaralarıyla şehirden kısa bir kaçış.', image: require('../assets/istanbul/princes-islands.jpg'), mapQuery: 'Büyükada İstanbul', credit: 'Ceylnbirol · Wikimedia Commons', imagePage: 'https://commons.wikimedia.org/wiki/File:View_of_Istanbul_from_Büyükada.jpg' },
  { id: 'bogaz', name: 'Boğaziçi ve Haliç', district: 'İstanbul', category: 'Manzara · Ulaşım', summary: 'İki kıtayı birleştiren su yolu, vapur yolculukları ve kıyı mahalleleriyle İstanbul deneyiminin kalbi.', image: require('../assets/istanbul/hero.jpg'), mapQuery: 'İstanbul Boğazı', credit: 'Maurice Flesier · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Bosphorus_and_Golden_Horn_view_from_Galata_Tower.jpg' },
  { id: 'sultanahmet', name: 'Sultanahmet Camii', district: 'Fatih', category: 'Cami', summary: 'Altı minaresi, geniş avlusu ve mavi İznik çinileriyle tarihî yarımadanın en güçlü Osmanlı silüetlerinden biridir.', image: require('../assets/istanbul/sultanahmet.jpg'), mapQuery: 'Sultanahmet Camii İstanbul', credit: 'Julian Lupyan · CC0', imagePage: 'https://commons.wikimedia.org/wiki/File:Sultan_Ahmed_Mosque_Front_Façade,_2024.jpg' },
  { id: 'suleymaniye', name: 'Süleymaniye Camii', district: 'Fatih', category: 'Cami', summary: 'Mimar Sinan’ın Kanuni Sultan Süleyman için tasarladığı külliye; Haliç manzarası ve dengeli mimarisiyle başyapıt kabul edilir.', image: require('../assets/istanbul/suleymaniye.jpg'), mapQuery: 'Süleymaniye Camii İstanbul', credit: 'İhsan Deniz Kılıçoğlu · CC BY-SA 3.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Süleymaniye_Mosque_exterior_view.JPG' },
  { id: 'camlica-camii', name: 'Büyük Çamlıca Camii', district: 'Üsküdar', category: 'Cami', summary: 'Çamlıca Tepesi’nde yükselen büyük külliye; altı minaresi, geniş avlusu, modern yorumlanan Osmanlı mimarisi ve şehir manzarasıyla öne çıkar.', image: require('../assets/istanbul/camlica-mosque.jpg'), mapQuery: 'Büyük Çamlıca Camii İstanbul', credit: 'Wikimedia Commons · CC BY 2.0', imagePage: 'https://commons.wikimedia.org/wiki/File:%C3%87aml%C4%B1ca_Mosque_front_view.jpg' },
  { id: 'eyup-sultan', name: 'Eyüp Sultan Camii ve Türbesi', district: 'Eyüpsultan', category: 'Türbe', summary: 'Ebu Eyyûb el-Ensârî’nin türbesi çevresinde gelişen külliye, İstanbul’un en önemli manevi ziyaret merkezlerindendir.', image: require('../assets/istanbul/eyup-sultan.jpg'), mapQuery: 'Eyüp Sultan Camii ve Türbesi İstanbul', credit: 'Ali Osman Dilekoğlu · Wikimedia Commons', imagePage: 'https://commons.wikimedia.org/wiki/File:Eyüp_Sultan_Camii_IMG_0227.jpg' },
  { id: 'fatih-turbesi', name: 'Fatih Sultan Mehmet Türbesi', district: 'Fatih', category: 'Türbe', summary: 'İstanbul’un fatihi II. Mehmed’in Fatih Camii haziresindeki türbesi; tarih ve manevi miras rotalarının temel duraklarındandır.', image: require('../assets/istanbul/fatih-tomb.jpg'), mapQuery: 'Fatih Sultan Mehmet Türbesi İstanbul', credit: 'Sitomon · CC BY-SA 2.0', imagePage: 'https://commons.wikimedia.org/wiki/File:II._Mehmed_tomb.jpg' },
  { id: 'hudayi', name: 'Aziz Mahmud Hüdayi Türbesi', district: 'Üsküdar', category: 'Türbe', summary: 'Üsküdar’daki külliye içinde bulunan türbe, tasavvuf tarihinin önemli isimlerinden Aziz Mahmud Hüdayi’ye adanmıştır.', image: require('../assets/istanbul/hudayi-tomb.jpg'), mapQuery: 'Aziz Mahmud Hüdayi Türbesi İstanbul', credit: 'M. Pınarcı · CC BY-SA 3.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Türbe_Ziyareti_003_-_panoramio.jpg' },
  { id: 'beylerbeyi', name: 'Beylerbeyi Sarayı', district: 'Üsküdar', category: 'Saray', summary: 'Boğaz’ın Anadolu yakasında yükselen 19. yüzyıl sarayı; deniz köşkleri, bahçeleri ve zarif dış cephesiyle öne çıkar.', image: require('../assets/istanbul/beylerbeyi.jpg'), mapQuery: 'Beylerbeyi Sarayı İstanbul', credit: 'José Luiz · Wikimedia Commons', imagePage: 'https://commons.wikimedia.org/wiki/File:Exterior_view_of_Beylerbeyi_Palace_(1).jpg' },
  { id: 'rumeli-hisari', name: 'Rumeli Hisarı', district: 'Sarıyer', category: 'Tarihî yapı', summary: 'Fatih Sultan Mehmet tarafından Boğaz’ın en dar noktalarından birinde yaptırılan görkemli kale ve açık hava tarih durağı.', image: require('../assets/istanbul/rumeli-fortress.jpg'), mapQuery: 'Rumeli Hisarı İstanbul', credit: 'Wikimedia Commons', imagePage: 'https://commons.wikimedia.org/wiki/File:Istanbul_Bosphorus_Rumelihisar%C4%B1_(Rumelian_Castle)_IMG_7804_1920.jpg' },
  { id: 'arkeoloji-muzeleri', name: 'İstanbul Arkeoloji Müzeleri', district: 'Fatih', category: 'Müze', summary: 'Arkeoloji Müzesi, Eski Şark Eserleri Müzesi ve Çinili Köşk’ten oluşan, farklı uygarlıklara uzanan büyük koleksiyon.', image: require('../assets/istanbul/archaeology-museum.jpg'), mapQuery: 'İstanbul Arkeoloji Müzeleri', credit: 'Yair Haklai · Wikimedia Commons', imagePage: 'https://commons.wikimedia.org/wiki/File:Istanbul_Archaeological_Museums_(main_building)-.jpg' },
  { id: 'rahmi-koc', name: 'Rahmi M. Koç Müzesi', district: 'Beyoğlu', category: 'Müze', summary: 'Haliç kıyısında sanayi, ulaşım ve iletişim tarihini otomobillerden deniz araçlarına uzanan koleksiyonlarla anlatan aile dostu müze.', image: require('../assets/istanbul/rahmi-koc.jpg'), mapQuery: 'Rahmi M. Koç Müzesi İstanbul', credit: 'A. Savin · Free Art License', imagePage: 'https://commons.wikimedia.org/wiki/File:Istanbul_asv2021-11_img14_Rahmi_Ko%C3%A7_Museum.jpg' },
  { id: 'kariye', name: 'Kariye Camii', district: 'Fatih', category: 'Çok kültürlü miras', summary: 'Bizans dönemindeki manastır kilisesi kökeni, mozaikleri ve freskleriyle İstanbul’un katmanlı kültür tarihinin seçkin yapılarından.', image: require('../assets/istanbul/kariye.jpg'), mapQuery: 'Kariye Camii İstanbul', credit: 'Gryffindor · Public domain', imagePage: 'https://commons.wikimedia.org/wiki/File:Chora_Church_Constantinople_2007_panorama_002.jpg' },
  { id: 'fener-balat', name: 'Fener & Balat', district: 'Fatih', category: 'Çok kültürlü miras', summary: 'Renkli evleri, tarihî ibadet yapıları, dar sokakları ve Haliç mahalle kültürüyle yürüyerek keşfedilen çok katmanlı rota.', image: require('../assets/istanbul/balat.jpg'), mapQuery: 'Fener Balat İstanbul', credit: 'Antoloji · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:Balat_houses.jpg' },
  { id: 'belgrad-ormani', name: 'Belgrad Ormanı', district: 'Sarıyer', category: 'Doğa · Sahil', summary: 'Yürüyüş ve koşu parkurları, bentleri ve geniş orman dokusuyla İstanbul’un kuzeyindeki en güçlü doğa kaçışlarından biri.', image: require('../assets/istanbul/belgrad-forest-new.jpg'), mapQuery: 'Belgrad Ormanı İstanbul', credit: 'KpokeJlJla · CC BY-SA 4.0', imagePage: 'https://commons.wikimedia.org/wiki/File:%D0%91%D0%B5%D0%BB%D0%B3%D1%80%D0%B0%D0%B4%D1%81%D0%BA%D0%B8%D0%B9_%D0%BB%D0%B5%D1%81,%D0%A1%D1%82%D0%B0%D0%BC%D0%B1%D1%83%D0%BB_-_1.JPG' },
];

const venueRows: [string, string, string][] = [
  ['Karaköy & Galata','Beyoğlu','Tasarım kafeleri, kahve ve yeni nesil mutfak'], ['Kadıköy Çarşı & Moda','Kadıköy','Sokak lezzetleri, meyhaneler ve üçüncü nesil kahve'],
  ['Beşiktaş Çarşı','Beşiktaş','Kahvaltı, balık ve hareketli öğrenci yaşamı'], ['Nişantaşı','Şişli','Pastaneler, dünya mutfağı ve şık kafeler'],
  ['Sultanahmet & Eminönü','Fatih','Tarihî lokantalar, köfte ve geleneksel tatlılar'], ['Arnavutköy & Bebek','Beşiktaş','Boğaz manzaralı restoran ve kafeler'],
  ['Kuzguncuk & Çengelköy','Üsküdar','Mahalle kafeleri, fırınlar ve Boğaz kıyısı'], ['Sarıyer & Rumelikavağı','Sarıyer','Balık restoranları ve kıyı kahvaltısı'],
];
export const istanbulVenueAreas = venueRows.map(([area,district,character]) => ({ area, district, character, cafeQuery: `en iyi kafeler ${area} İstanbul`, restaurantQuery: `en iyi restoranlar ${area} İstanbul` }));

export const istanbulFoodGuide = [
  { dish: 'Balık ekmek', area: 'Eminönü · Karaköy', note: 'Haliç ve Boğaz manzarası eşliğinde, kıyıdaki geleneksel balık-ekmek noktalarında dene.', mapQuery: 'balık ekmek Eminönü Karaköy İstanbul' },
  { dish: 'Sultanahmet köftesi', area: 'Sultanahmet · Fatih', note: 'Tarihî yarımadadaki köftecilerde piyaz ve ayran eşliğinde servis edilen klasik yorumu tercih et.', mapQuery: 'Sultanahmet köftesi Fatih İstanbul' },
  { dish: 'Kumpir', area: 'Ortaköy · Beşiktaş', note: 'Ortaköy Meydanı çevresindeki kumpircilerde malzemelerini seçerek Boğaz kıyısında tadabilirsin.', mapQuery: 'kumpir Ortaköy Beşiktaş İstanbul' },
  { dish: 'Kanlıca yoğurdu', area: 'Kanlıca · Beykoz', note: 'Vapur iskelesi çevresinde pudra şekeriyle sunulan geleneksel Kanlıca yoğurdunu dene.', mapQuery: 'Kanlıca yoğurdu Beykoz İstanbul' },
  { dish: 'Sarıyer böreği', area: 'Sarıyer Merkez', note: 'Sarıyer’in köklü börekçilerinde kıymalı, peynirli veya kuş üzümlü çeşitlerini sıcak olarak ara.', mapQuery: 'Sarıyer böreği Sarıyer İstanbul' },
  { dish: 'Vefa bozası', area: 'Vefa · Fatih', note: 'Kış aylarında tarçın ve leblebiyle sunulan koyu kıvamlı geleneksel bozayı tarihî Vefa çevresinde tat.', mapQuery: 'boza Vefa Fatih İstanbul' },
  { dish: 'Profiterol', area: 'Beyoğlu', note: 'İstiklal Caddesi ve çevresindeki geleneksel pastanelerde yoğun çikolata soslu İstanbul klasiğini dene.', mapQuery: 'profiterol Beyoğlu İstanbul' },
  { dish: 'Moda dondurması', area: 'Moda · Kadıköy', note: 'Moda sahiline uzanan yürüyüşte mahalle dondurmacılarının mevsimlik ve klasik çeşitlerini keşfet.', mapQuery: 'dondurma Moda Kadıköy İstanbul' },
];

export const istanbulAccommodations = [
  { area: 'Sultanahmet', district: 'Fatih', category: 'Tarih', bestFor: 'İlk ziyaret · tarih', character: 'Ayasofya, Topkapı ve tarihî yarımadaya yürüyerek ulaşmak isteyenler için.', level: 'Karma', mapQuery: 'otel konaklama Sultanahmet Fatih İstanbul' },
  { area: 'Taksim & Beyoğlu', district: 'Beyoğlu', category: 'Gece hayatı', bestFor: 'Kültür · gece hayatı', character: 'İstiklal, müzeler, restoranlar ve merkezi ulaşımın yakınında.', level: 'Karma', mapQuery: 'otel konaklama Taksim Beyoğlu İstanbul' },
  { area: 'Beşiktaş & Boğaz', district: 'Beşiktaş', category: 'Merkezi ulaşım', bestFor: 'Boğaz · merkezi ulaşım', character: 'Vapur bağlantıları, saraylar ve Boğaz kıyısına yakın şehir otelleri.', level: 'Lüks', mapQuery: 'otel konaklama Beşiktaş Boğaz İstanbul' },
  { area: 'Kadıköy & Moda', district: 'Kadıköy', category: 'Yerel yaşam', bestFor: 'Yerel yaşam · yeme içme', character: 'Anadolu Yakası’nın çarşı, sahil, kafe ve gece yaşamına yakın.', level: 'Orta', mapQuery: 'otel konaklama Kadıköy Moda İstanbul' },
  { area: 'Şişli & Nişantaşı', district: 'Şişli', category: 'İş & alışveriş', bestFor: 'Alışveriş · iş seyahati', character: 'Metro, alışveriş, iş merkezleri ve şehir otelleri için güçlü bir üs.', level: 'Lüks', mapQuery: 'otel konaklama Şişli Nişantaşı İstanbul' },
  { area: 'Büyükada', district: 'Adalar', category: 'Sakin tatil', bestFor: 'Sakinlik · hafta sonu', character: 'Tarihî köşk atmosferinde butik otel ve pansiyon seçenekleri.', level: 'Orta', mapQuery: 'otel butik otel pansiyon Büyükada İstanbul' },
];

export const istanbulRoutes = [
  { title: 'Tarihî Yarımada', duration: '1 tam gün', color: '#75513B', stops: ['Ayasofya','Sultanahmet Camii','Topkapı Sarayı','Yerebatan Sarnıcı','Kapalıçarşı'] },
  { title: 'Galata’dan Boğaz’a', duration: '1 tam gün', color: '#315F53', stops: ['Galata Kulesi','Karaköy','Dolmabahçe Sarayı','Ortaköy','Bebek'] },
  { title: 'Anadolu Yakası', duration: '1 tam gün', color: '#477A89', stops: ['Kuzguncuk','Üsküdar Sahili','Kadıköy Çarşı','Moda Sahili','Caddebostan'] },
  { title: 'Adalar günü', duration: '1 tam gün', color: '#6B7252', stops: ['Büyükada İskelesi','Aya Yorgi Yokuşu','Büyükada Köşkleri','Dilburnu'] },
  { title: 'Müzeler & Haliç', duration: '1 tam gün', color: '#73566F', stops: ['İstanbul Arkeoloji Müzeleri','Galata Kulesi','Rahmi M. Koç Müzesi','Miniatürk'] },
  { title: 'Çok kültürlü miras', duration: '1 tam gün', color: '#A26448', stops: ['Kariye Camii','Fener Rum Patrikhanesi','Balat','Sveti Stefan Kilisesi'] },
  { title: 'Orman & Boğaz', duration: '1 tam gün', color: '#3F6650', stops: ['Belgrad Ormanı','Emirgan Korusu','Rumeli Hisarı','Bebek Sahili'] },
];

export const istanbulTransport = [
  { icon: 'M', name: 'Metro', description: 'Raylı sistemle iki yakadaki merkezlere hızlı erişim ve aktarma noktaları.', mapQuery: 'İstanbul metro istasyonları' },
  { icon: 'MR', name: 'Marmaray', description: 'Boğaz’ın altından Avrupa ve Anadolu yakalarını birbirine bağlayan banliyö hattı.', mapQuery: 'İstanbul Marmaray istasyonları' },
  { icon: 'V', name: 'Vapur & deniz ulaşımı', description: 'Boğaz, Haliç ve Adalar arasında manzaralı şehir hatları bağlantıları.', mapQuery: 'İstanbul vapur iskeleleri' },
  { icon: 'MB', name: 'Metrobüs', description: 'Ana arter boyunca iki yakayı 24 saat çalışan otobüs hattıyla bağlayan sistem.', mapQuery: 'İstanbul metrobüs durakları' },
  { icon: 'T', name: 'Tramvay & füniküler', description: 'Tarihî yarımada, Beyoğlu ve Boğaz bağlantılarındaki kısa şehir hatları.', mapQuery: 'İstanbul tramvay füniküler istasyonları' },
  { icon: '✈', name: 'Havalimanı ulaşımı', description: 'İstanbul ve Sabiha Gökçen havalimanlarına toplu taşıma seçenekleri.', mapQuery: 'İstanbul havalimanı toplu taşıma' },
];
